# k8s/frontend-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskpipeline-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskpipeline-frontend
  template:
    metadata:
      labels:
        app: taskpipeline-frontend
    spec:
      containers:
      - name: frontend
        image: mariawahid/taskpipeline-frontend:latest
        ports:
        - containerPort: 3000  # Ye React ka default port hai
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: taskpipeline-frontend
  ports:
    - port: 3000         # Service port
      targetPort: 3000   # Container ka port (MATCH HONA ZAROORI HAI)
      nodePort: 30080    # Browser mein 30080 se access karenge