---
- name: Verify and Enforce Base DevOps Tools
  hosts: localhost
  become: true
  tasks:
    - name: Ensure Package Cache is Updated
      apt:
        update_cache: yes
      ignore_errors: yes

    - name: Verify Docker Service is Active
      service:
        name: docker
        state: started

    - name: Verify Jenkins Service is Active
      service:
        name: jenkins
        state: started

# =========================================================================
# 🚀 TARGETING PRODUCTION HOSTS (16.171.42.170)
# =========================================================================
- name: Deploy TaskPipeline Modules to Production K8s
  hosts: production
  become: true
  tasks:
    - name: Apply Backend Deployment to MicroK8s
      shell: "microk8s kubectl apply -f /var/lib/jenkins/workspace/TaskPipeline-Job/k8s/backend-deployment.yaml"

    - name: Apply Frontend Deployment to MicroK8s
      shell: "microk8s kubectl apply -f /var/lib/jenkins/workspace/TaskPipeline-Job/k8s/frontend-deployment.yaml"

    - name: Wait for Pods
      pause:
        seconds: 10

    - name: Show Pods Status
      shell: "microk8s kubectl get pods -A"
      register: pods_output

    - name: Print Pods
      debug:
        var: pods_output.stdout_lines